using System.Text.Json;
namespace ProductManagement.Helper;

internal partial class Helper
{
    /// <summary>Deserializes JSON request body with error handling.</summary>
    /// <typeparam name="T">Target deserialization type.</typeparam>
    /// <param name="request">HTTP request with JSON body.</param>
    /// <returns>Deserialized object or error result.</returns>
    /// <remarks>helper method below was generated by AI - DeepSeek to capture
    /// malformed JSON.</remarks>
    // copied from previous code for minimal API 
    
    public static async Task<(T? value, IResult? error)> TryReadJsonBodyAsync<T>
        (HttpRequest request)
    {
        try
        {
            request.EnableBuffering();
            using StreamReader sr = new(request.Body, leaveOpen: true);
            string body = await sr.ReadToEndAsync();
            request.Body.Position = 0;

            if (string.IsNullOrWhiteSpace(body))
                return (default, BadRequest("Request body is empty"));

            JsonSerializerOptions options = new()
            {
                PropertyNameCaseInsensitive = true
            };

            try
            {
                T? obj = JsonSerializer.Deserialize<T>(body, options);
                if (obj == null)
                {
                    WriteLine($"\nUnable to parse JSON body");    
                    WriteLine(TypedResults.Ok("Test"));
                    return (default, UnprocessableEntity("Unable to parse JSON body"));
                }
                return (obj, null);
            }
            catch (JsonException jex)
            {
                WriteLine($"\nMalformed JSON: {jex.Message}");
                return (default, UnprocessableEntity("Malformed JSON in request body"));
            }
            catch (Exception ex)
            {
                WriteLine($"\nUnexpected error deserializing JSON: {ex.Message}");
                return (default, UnprocessableEntity("Malformed JSON in request body"));
            }
        }
        catch (Exception ex)
        {
            WriteLine($"\nError reading request body: {ex.Message}");
            return (default, UnprocessableEntity("Malformed JSON in request body"));
        }
    }

    public class ValidateJsonFilter : IEndpointFilter
    {
        public async ValueTask<object?> InvokeAsync(
            EndpointFilterInvocationContext context,
            EndpointFilterDelegate next)
        {
            // Access the request
            var request = context.HttpContext.Request;
        
            // Try to read and validate JSON
            if (!await TryValidateJson(request))
            {
                return Results.BadRequest("Invalid JSON format");
            }
        
            return await next(context);
        }
    
        private async Task<bool> TryValidateJson(HttpRequest request)
        {
            // Your TryReadJsonBodyAsync logic here

            (InputDataConverter? dataConverter, IResult? error) =
                await TryReadJsonBodyAsync<InputDataConverter>(request);
            if (error != null)
            {
                return false;
            }


            return true;
        }
    }
}