using static ProductManagement.Helper.Helper;
using Microsoft.EntityFrameworkCore;

namespace ProductManagement;

// This file was auto generated by an EF tool from a database file which I
// created first

/// <summary>Database context for Product Management operations.</summary>
public partial class ProductManagementDb : DbContext
{
    public ProductManagementDb()
    {
    }

    /// <summary>Initializes a new instance of the ProductManagementDb with options.</summary>
    /// <param name="options">The DbContext options for configuration.</param>
    public ProductManagementDb(DbContextOptions<ProductManagementDb> options)
        : base(options)
    {
    }

    /// <summary>Gets or sets the Products DbSet for database operations.</summary>
    public virtual DbSet<Product> Products { get; set; }

    /// <summary>Configures the database connection for SQLite.</summary>
    /// <param name="optionsBuilder">The options builder to configure.</param>
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlite(DevConfiguration["Database:Details:ConnectionString"]);
    }

    /// <summary>Configures the entity model during creation.</summary>
    /// <param name="modelBuilder">The model builder to configure.</param>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}